spring:
  application:
    name: video-api
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: ${DATABASE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
springdoc:
  swagger-ui:
    path: /api-docs.html
  api-docs:
    path: /api-docs
info:
  application:
    name: video-api
    description: Api de Videos
    version: 0.0.1