spring:
  application:
    name: video-api
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
springdoc:
  swagger-ui:
    path: /api-docs.html
  api-docs:
    path: /api-docs
info:
  application:
    name: video-api
    description: API for video management
    version: 0.0.1
flyway:
  enabled: false